### ISSUE TITLE
Target class [App\User] does not exist.

### ISSUE THREAD

**Issue by TensaiKato** [Matheussg42/to-do-list-laravel#19]
Olá,

Estou usando o Laravel 8.x e quando faço um POST para a url 'api/register' com o JSON, estou recebendo uma mensagem de 'Target class [App\User] does not exist.' será que pode ser algo relacionado a versão do Laravel?

Obrigado!

**Comment by Matheussg42** [comment]
Olá Tensai. Tudo tranquilo?

Primeiramente desculpa a demora.
No projeto utilizei a versão 7.9.2, porém atualizei para simular a situação e a request funcionou.

Dentre os motivos que posso imaginar, pode ser `namespace` dentro do `User Model`, ou no momento de declarar o model dentro do `UserController`, ou na criação da rota. Se quiser, disponibiliza o código que eu dou uma olhada nele pra poder te ajudar.

Caso ainda tenha o erro, fique a vontade de me chamar no Discord: Matheus S.#3938
